# Generated by Django 5.0.4 on 2024-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tagline', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fruit_images/')),
            ],
        ),
    ]
